Refact no arquivo de CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,7 +9,7 @@ on:
       - master
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     services:
@@ -76,13 +76,27 @@ jobs:
           ${{ runner.os }}-maven-
 
     - name: Build and test with Maven
-      run: mvn clean test jacoco:report 
+      run: mvn clean package jacoco:report --fail-at-end
+      
+    - name: Verify JAR generation
+      run: |
+          if [ ! -f target/voto-*.jar ]; then
+            echo "JAR file not found!" && exit 1
+          fi 
 
     - name: Upload JaCoCo report
       uses: actions/upload-artifact@v3
       with:
         name: jacoco-report
         path: target/site/jacoco
+
+  docker:
+    runs-on: ubuntu-latest
+    needs: test
+    
+    steps:
+    - name: Check out code
+      uses: actions/checkout@v3
 
     - name: Build Docker Image
       run: docker build -t voto-app .
